#!/bin/bash --
# by pts@fazekas.hu at Thu Jan  7 11:37:17 CET 2016
set -ex
# Running `perl' to change whitespace generated by `cpp'.
cpp -DCFG_LANG_GAWK=1 -E muzcat.c | grep -v '^#' | grep -v '^ *$' |
    perl -0777 -pe '
        s@\b(\w+) \(\)@$1()@g;
        s@(\bfunction +(\w+)\s*\([^)]+\)\s*{)@ my $x=$1; $x=~y/\n/ /; $x @ge
        ' >zcat.gawk
gawk -f zcat.gawk </dev/null  # Check for compile errors.
# In newer versions of Gawk, `LC_CTYPE=C gawk' can be replaced with `gawk -b'.
#rm -f test; time LC_CTYPE=C gawk -f zcat.gawk <bash.gz >test ; cmp bash.file test
#rm -f test; time LC_CTYPE=C gawk -f zcat.gawk ./a.out <random.file.gz >test ; cmp random.file test
#rm -f test; time LC_CTYPE=C gawk -f zcat.gawk ./a.out <misc.file.gz >test ; cmp misc.file test
echo OK
